### ISSUE TITLE
timeout should use time zone

### ISSUE THREAD

**Issue by mlyubarskyy** [CodingZeal/padlock#2]
https://github.com/CodingZeal/padlock/blob/master/lib/padlock.rb#L48

**Comment by mlyubarskyy** [comment]
same as #touch

**Comment by acuppy** [comment]
Excellent!  Thank you for catching that.  Do you want to issue a pull request? (Get credit for the continuation 😉)

**Comment by acuppy** [comment]
*contribution

**Comment by mlyubarskyy** [comment]
https://github.com/CodingZeal/padlock/pull/3
